### ISSUE TITLE
Can I go directly to a group?

### ISSUE THREAD

**Issue by nikivdev** [Jamesits/alfred-workflow-telegram#2]
I can go directly to some user by assigning a hotkey and passing in the name of the user.

Can I do the same but for the group?

Thank you for any help.

**Comment by Jamesits** [comment]
I've updated this workflow. From now on, if your group have a `@username`, use `tg group_username`; otherwise you need to grab the invite link like `https://telegram.me/joinchat/group_token` and use `tg joinchat group_token` to find your group. I haven't find any way to open a group without username or invite link.

**Comment by nikivdev** [comment]
Thank you for such a quick addition. 

How do I see or get the username of the group, I don't really see it anywhere.

**Comment by Jamesits** [comment]
If there is one, you can see it at its detail page just like any normal user. Otherwise seek for its invite link.

Supergroup is a modified version of "commentable channel" which once showed up in the code but is never published. That's why a group may have an username.

**Comment by nikivdev** [comment]
So I should do something like this? 

![2016-08-31 at 17 08](https://cloud.githubusercontent.com/assets/6391776/18134148/a8896064-6f9d-11e6-88c6-5eaae1d14a68.png)

This doesn't seem to work for me : 

![2016-08-31 at 17 09](https://cloud.githubusercontent.com/assets/6391776/18134152/aea2e24a-6f9d-11e6-8b3f-f919cfde8705.png)

This is where I got the invite link for the group : 

![2016-08-31 at 17 10](https://cloud.githubusercontent.com/assets/6391776/18134202/ecf8643e-6f9d-11e6-95f5-fb16e0d2bd27.png)

**Comment by Jamesits** [comment]
Strip the URL, leave only the argument. The full alfred query should be like `tg joinchat BBKnQQpA……`

**Comment by nikivdev** [comment]
Thank you a lot, this works wonderfully.
